### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by NandanDesai** [krisives/voltage#1]
Hi! Really appreciate your work in this project. 
I am trying to use this project as a module in my project. I tried to run the your code as it is, but it is crashing. 

Here is a complete stack trace:
```
PHP Fatal error:  Uncaught Exception: Not enough memory for even a single piece in /var/www/html/voltage/classes/PieceCache.php:448
Stack trace:
#0 /var/www/html/voltage/classes/PieceCache.php(20): PieceCache::calculateMaxPieces(524288)
#1 /var/www/html/voltage/classes/Download.php(37): PieceCache->__construct(Object(Torrent), '/var/www/html/v...')
#2 /var/www/html/voltage/voltage.php(47): Download->__construct(Object(Torrent), '/var/www/html/v...')
#3 {main}
  thrown in /var/www/html/voltage/classes/PieceCache.php on line 448
```

I would really appreciate if you help me out with this. Thanks!

**Comment by krisives** [comment]
There are two ways you can work around this problem:

* Increase your `memory_limit` for PHP, something like 128MB or 256MB is common. Most torrents have anywhere from 256K to 4MB per piece, although very large torrents may have bigger pieces. The error is thrown if a single piece cannot fit in memory (usually because of very tight memory_limit)

* Modify the function to return a constant, like 1, which isn't great for performance but will avoid this failing since it's possible that PHP has enough memory to fit a single piece in memory but the estimation is incorrect - I made a branch for that for you here: https://github.com/krisives/voltage/tree/memory-workaround

**Comment by NandanDesai** [comment]
The problem was with `ini_get('memory_limit');` which was returning -1 at (https://github.com/krisives/voltage/blob/fe555aa40c7d07f89cce1e228677955eb2c3cdfa/classes/PieceCache.php#L424).

So I manually assigned `$limit="256M";` at that line and it was fine. But your solution is working perfectly. Thanks!

I have a few doubts.

- The CPU usage increases to 50 to 60 percent when downloading the file. Is there anything that can be done here? 

- The file chunks are not getting downloaded in order. So, I am not able to play a video file when it is getting downloaded. There are a few Bittorrent clients that force the files to be downloaded in proper order. Can that same behaviour be achieved here?

**Comment by krisives** [comment]
> The file chunks are not getting downloaded in order. So, I am not able to play a video file when it is getting downloaded. There are a few Bittorrent clients that force the files to be downloaded in proper order. Can that same behaviour be achieved here?

Try modifying this line to not use rand() but instead return something like `$unfinished[0]` which should request the next piece. That won't have great download performance because it will request the same piece from multiple peers, but you get the idea:

https://github.com/krisives/voltage/blob/fe555aa40c7d07f89cce1e228677955eb2c3cdfa/classes/PieceCache.php#L31

**Comment by NandanDesai** [comment]
OK, I'll try it out. Thanks!
